Feature/simplify metadata argument passing
ml6team/express pull request #24
Opened 2023-04-03 09:03 UTC by PhilippeMoussalli

PR that simplifies the way the way that components arguments are built and passed to the components. 

The previous implementation relied on the user providing both the component arguments and the metadata arguments. The latter is something that the end-user does not need to take care off. It also makes the arguments passed to each component more straightforward (args, manifest input, mainfest output).

**Note:** the PR branches off this [PR](https://github.com/ml6team/express/pull/21)

2023-04-04 06:39 UTC, NielsRogge commented on examples/components/single_node/hf_datasets/data_loading_hf_datasets.py
> +             json dict string
I guess we can't get around the "json dict string", which is a bit weird

2023-04-04 06:42 UTC, NielsRogge commented on express/components/common.py
> +        args_dict = json.loads(parsed_args.args)
Maybe the json.loads can be directly in the `_parse_args` method?

2023-04-04 06:43 UTC, NielsRogge commented on express/components/common.py
> +        args_dict = json.loads(parsed_args.args)
Same comment here

2023-04-04 06:48 UTC, NielsRogge commented on examples/components/single_node/pandas/README.MD
> +--args '{"project_id": "soy-audio-379412", "run_id":"test","component_name":"test_component", \
```suggestion
--args '{"project_id": "soy-audio-379412", "run_id":"test", "component_name":"test_component", \
```

2023-04-04 06:49 UTC, NielsRogge commented on examples/components/single_node/pandas/README.MD
> +--args '{"project_id": "soy-audio-379412", "run_id":"test","component_name":"test_component", \
Isn't it a bit weird that we need to pass the name of the component to the component itself?

2023-04-04 09:05 UTC, NielsRogge commented on examples/components/single_node/pandas/README.MD
> +--args '{"project_id": "soy-audio-379412", "run_id":"test","component_name":"test_component", \
Run_id and project_id makes sense as metadata as those are different each time you run a component, but the name of the component seems inherent to the component itself

2023-04-04 09:06 UTC, NielsRogge approved these changes
Thanks for improving!

2023-04-04 11:33 UTC, NielsRogge requested changes
On second thought, it might be better to expose the individual arguments that a component expects in its specification. By just accepting `args` it may be unclear that a component for instance requires `model_id` and `batch_size`. 

It might be better that the user specifies in the function (as arguments) or in the class (as attributes) which arguments are required, which are then automatically turned into CLI arguments (a bit like how Google's [Fire](https://github.com/google/python-fire) works).

2023-04-07 11:43 UTC, RobbeSneyders commented on examples/pipelines/hf_dataset_pipeline/components/add_captions/component.yaml
> +    - name: args
Why do we pass these arguments as json instead of as separate arguments?

2023-04-11 08:32 UTC, NielsRogge commented
PR #27 updates the way metadata is updated, so it depends on the review of that PR regarding how we can proceed

2023-04-19 07:28 UTC, closed without merging